apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pulceo-monitoring-service

spec:
  rules:
    - http:
        paths:
          - path: /api/v1/metric-requests
            pathType: Prefix
            backend:
              service:
                name:  pulceo-monitoring-service
                port:
                  number: 7777
          - path: /register
            pathType: Prefix
            backend:
              service:
                name: pulceo-monitoring-service
                port:
                  number: 7777
          - path: /api/v1/node-link-metrics
            pathType: Prefix
            backend:
              service:
                name: pulceo-monitoring-service
                port:
                  number: 7777
          - path: /pms/health
            pathType: Exact
            backend:
              service:
                name: pulceo-monitoring-service
                port:
                  number: 7777

---
apiVersion: v1
kind: Service
metadata:
  name: pulceo-monitoring-service

spec:
  ports:
    - protocol: TCP
      name: web
      port: 7777
  selector:
    app: pulceo-monitoring-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulceo-monitoring-service
  labels:
    app: pulceo-monitoring-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulceo-monitoring-service
  template:
    metadata:
      labels:
        app: pulceo-monitoring-service
    spec:
      containers:
        - name: pulceo-monitoring-service
          image: ghcr.io/spboehm/pulceo-monitoring-service:v1.0.0rc4
          imagePullPolicy: Always
          volumeMounts:
            - name: psm-pv-db
              mountPath: /db
          env:
            - name: PRM_HOST
              valueFrom:
                configMapKeyRef:
                  name: pms-configmap
                  key: PRM_HOST
            - name: PSM_HOST
              valueFrom:
                configMapKeyRef:
                  name: pms-configmap
                  key: PSM_HOST
            - name: INFLUXDB_URL
              valueFrom:
                configMapKeyRef:
                  name: pms-configmap
                  key: INFLUXDB_URL
            - name: INFLUXDB_ORG
              valueFrom:
                configMapKeyRef:
                  name: pms-configmap
                  key: INFLUXDB_ORG
            - name: INFLUXDB_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: pms-configmap
                  key: INFLUXDB_BUCKET
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pms-credentials
                  key: INFLUXDB_TOKEN
            - name: PNA_MQTT_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: pms-credentials
                  key: PNA_MQTT_BROKER_URL
            - name: PNA_MQTT_CLIENT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pms-credentials
                  key: PNA_MQTT_CLIENT_USERNAME
            - name: PNA_MQTT_CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pms-credentials
                  key: PNA_MQTT_CLIENT_PASSWORD
          ports:
            - containerPort: 7777
              name: web
      volumes:
        - name: psm-pv-db
          persistentVolumeClaim:
            claimName: psm-pv-db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psm-pv-db
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: pms-influxdb-lb

spec:
  ports:
    - protocol: TCP
      name: web
      port: 8089
      targetPort: 8086
  selector:
    app: pms-influxdb
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: pms-influxdb

spec:
  ports:
    - protocol: TCP
      name: web
      port: 8086
  selector:
    app: pms-influxdb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms-influxdb
  labels:
    app: pms-influxdb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pms-influxdb
  template:
    metadata:
      labels:
        app: pms-influxdb
    spec:
      containers:
        - name: pms-influxdb
          image: influxdb:2.7.5
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: org
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: bucket
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pms-credentials
                  key: DOCKER_INFLUXDB_INIT_USERNAME
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pms-credentials
                  key: DOCKER_INFLUXDB_INIT_PASSWORD
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pms-credentials
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          volumeMounts:
            - name: pms-pv-db
              mountPath: /db
            - name: pms-influxdb-pv-data
              mountPath: /var/lib/influxdb2
            - name: pms-influxdb-pv-config
              mountPath: /etc/influxdb2
          ports:
            - containerPort: 8086
              name: web
      volumes:
        - name: pms-pv-db
          persistentVolumeClaim:
            claimName: pms-pv-db
        - name: pms-influxdb-pv-data
          persistentVolumeClaim:
            claimName: pms-influxdb-pv-data
        - name: pms-influxdb-pv-config
          persistentVolumeClaim:
            claimName: pms-influxdb-pv-config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-pv-db
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-influxdb-pv-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-influxdb-pv-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
